#pragma once

#define NETLINK_EXCHANGE_PROTOCOL 31
#define NETLINK_EXCHANGE_MAX_MESSAGE_SIZE 256

#define NETLINK_EXCHANGE_REQUEST 0x10
#define NETLINK_EXCHANGE_RESPONSE 0x11

#define NETLINK_EXCHANGE_RESPONSE_PREFIX "kernel received: "
